spring:
  config:
    active:
      on-profile: "dev"

build:
  version: "1.0"

loan:
  message: "Hello from Luke Dev 51!! DEV ENV"
  contact-details:
    name: "Luke - Dev"
    email: "luke.dev.51@gmail.com"
  on-call-support:
    - 0984138630
    - 0965021460